//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace innovationTask.Models
{
    using innovationTask.Validation;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Order
    {
        public int orderId { get; set; }
        [Required]
        [Display(Name ="Order Status")]
        [CustomDataAnnotationValidation("Received", "Completed",ErrorMessage = "You should enter just (Completed or Received)")]
        public string orderStatus { get; set; }
        [Required]
        [Display(Name = "Shipping Status")]
        [CustomDataAnnotationValidation("shipped", "Rejected", ErrorMessage = "You should enter just (Shipped or Rejected)")]
        public string shippingStatus { get; set; }
    }
}
